---
title: "Condition-specific utility calculation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Condition_specific_utility_calculation}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
bibliography: REFERENCES.bib
link-citations: yes
citation_package: natbib
biblio-style: vancouver
urlcolor: blue
---

```{r setup, include = FALSE, results = 'hide', warning = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.pos = 'H'
)

#library(readxl)
#library(data.table)

#knitr::opts_knit$set(root.dir = "//tsclient/X/ScHARR/PR_STAPM/Code/R_packages/qalyr")
```

## HODaR data
The `qalyr` package contains functions to read and process the HODAR data [@currie2005routine] into a suitable form for use in our modelling. The raw data is in two files: the inpatient data and the survey data. The raw data was provided to us with only episodes with at least one tobacco- or alcohol-related diagnosis code in it. 

With this data we want to: 
* Estimate utilities for each condition in the tobacco and alcohol disease list. 
* Estimate utilities for the whole population, stratified by age, sex, and if possible IMD quintile. (remember this is a hospital population)
* Estimate age-sex-condition specific utilities. 

Extra:
* Estimate utilities for each conditions in the tobacco and alcohol disease list, stratified by tobacco and alcohol consumption. 
* Estimate utilities for the whol popuation, stratified by age, sex, possibly IMD quintile, and tobacco and alcohol consumption. 

To do this, we need to combine the two data. The only variable we have to match on is the patient ID. Due to some patients having multiple admissions within the time between surveys were sent, we have designed a set of rules for matching.  


## Merging the inpatient data and the survey data 
The function `merge_data()` merges the two datasets provided: inpatient data and survey data. These are provided at episode level, for episodes with at least one diagnostic code that is tobacco or alcohol-related. 

### Format inpatient data 
The function loops through each diagnosis column in the inpatient data and searches for ICD-10 codes that match alcohol/tobacco-related conditions (using the lkup table). A new column is created for each condition in the lkup table (alcohol and tobacco related conditions) and stores a binary variable, 1 if the patient had a diagnostic code that matched that condition, and 0 if not. 

### Episode to admission level 
Episodes are then collapsed into admissions. All conditions that were included across the admission are retained (sum across episodes). This leaves a row for each admission, with a column for each condition signifying whether they had any diagnostic code related to alcohol or tobacco. 

### Match data
The function reads in the survey data, and matches it to the inpatient data by 'Patient_Number'. Three rules are implemented to make sure the surveys are matched to the appropriate admissions to the survey: 
1. The admission must be discharged before the survey was sent, 
2. The time between the patient being discharged and the survey being sent must be under a year,
3. If an admission was matched with two surveys, the admission is matched to the earliest survey. 


## Objective one: Calculating condition-specific utilities 
The function `CalcUtils()` calculates the average utility for each alcohol/tobacco-related condition. This is done by averaging the utility values for each condition across all surveys.  

A utility value is extracted for each condition based on ICD-10 codes. While utilities can be extracted per age and sex group, only the mean utility is extracted because direct analysis at a condition/age level involves very small sample sizes. 

For conditions where no utility data was available, utilities were assumed to be similar to close conditions. Thus, utilities for alcohol induced Cushing syndrome were assumed to be similar to alcoholic polyneuropathy. Utilities for alcoholic myopathy were assumed to be similar to utilities for alcohol cardiomyopathy. The utility for excessive blood level of alcohol was assumed to be similar to evidence of alcohol involvement determined by blood alcohol level. Utilities for drowning were assumed to be similar to transport injuries. Finally, utilities for other intentional injuries were assumed to be similar to other unintentional injuries. \href{https://www.nice.org.uk/guidance/ph24/evidence/economic-modelling-report-371533357}{SAPM model}.

## Objective two: General population utilities
We use published estimates to inform our general population utilities. Baseline HSUVs profiles are assumed to be equal to the profile of HSUVs from the general population, adjusted for age and sex (i.e. all individuals irrespective of disease history). A formula was created using the Health Survey for England (n = 26,679). The code in data_raw `Prep_GenPopUtil.R` creates a new data table where all combinations of age and sex are present - this is embedded as package data. Age-sex-specific general population utilities are calculated using the formula from Ara and Brazier [-@Ara2010]:

$$Baseline\ utility = 0.9508566 + 0.0212126\ sex - 0.0002587\ age - 0.0000332\ age^2  \ \ \ \ \ \ \ \ \ \ \ [1]$$
## Objective three: Adjust condition-specific utilities by age and sex 
To calculate age-sex-condition specific HSUVs, we calculate a multiplier. The multiplier is a constant proportional effect that is applied to the age-sex-baseline HSUVs to calculate the age-sex-condition-specific HSUVs.   

### Calculate multiplier 
The multiplier for a condition is obtained using the HSUV for the condition and the baseline HSUV for individuals with the same mean age and proportion of males as the condition. 

In order to calculate age-sex-condition specific HSUVs, we need to calculate the mean age and proportion of males in the condition population. We do this by using the merged HODAR and inpatient data collapsed into survey level data. We average across the surveys for each condition to calculate the average age and proportion of males with that condition. 

Need to calculate the matched age-sex-specific general population utility using Eqn [1]. In the function `Adj_cond_utils()`, we read in the general populatin utilities (`qalyr::GenPopUtil`), the mean age and sex by condition, and the condition-specific utilities. Building on Age_Sex_data, we create a column for the matched general population HSUV using the mean age and proportion of males as inputs to Eqn [1]. The matched general population HSUV gives the general population HSUV for the same population as those who get sick from that condition. This is a way to match the two HSUVs to calculate the multiplier. 

The multiplier is simply the condition-specific HSUV ($U_c$) divided by the matched general population HSUV ($U_{MGP}$). This gives a constant. 

$$ Multiplier_{c} = \frac{U_{c}}{U_{MGP}} $$
### Adjusted condition HSUVs
To calculate the age-sex-condition-specific HSUVs is then simply a case of multiplying the age-sex-specific general population HSUVs ($U_{GP}(a,s)$) by the multiplier for each condition. 


$$ U_{c}(a,s) = U_{GP}(a,s) * Multiplier_{c}$$


## References 
